### ISSUE TITLE
Unable to start 

### ISSUE THREAD

**Issue by dkfi** [pzim/reaktor#41]
root@puppet:~/reaktor# rake start
rake aborted!
LoadError: cannot load such file -- resque-retry
/root/reaktor/lib/reaktor/jobs/event.rb:2:in `<top (required)>'
/root/reaktor/lib/reaktor/event_jobs.rb:3:in `<module:EventJobs>'
/root/reaktor/lib/reaktor/event_jobs.rb:2:in `<module:Reaktor>'
/root/reaktor/lib/reaktor/event_jobs.rb:1:in `<top (required)>'
/root/reaktor/Rakefile:5:in `<top (required)>'
(See full trace by running task with --trace)

**Comment by dkfi** [comment]
inserted by mistake. See #42
